### ISSUE TITLE
'Common' does not exist in namespace 'Microsoft.TeamFoundation.Git'

### ISSUE THREAD

**Issue by FokkoVeegens** [ALM-Rangers/Extracting-effective-permissions-from-TFS#2]
Hi,

Seems like the project references Microsoft.TeamFoundation.Git.Common, but that assembly is not available. The NuGet restore only gets Microsoft.TeamFoundation.Git.Client.dll. I searched the installation dirs of both TFS 2015.3 and 2017, but I couldn't find it. Because of this, the project doesn't build. Do you have any alternatives to this assembly? 

The error occurs in Helpers.cs, line 93 to 99; Error CS0234 The type or namespace name 'Common' does not exist in the namespace 'Microsoft.TeamFoundation.Git' (are you missing an assembly reference?)

**Comment by hkamel** [comment]
Hello @FokkoVeegens you need [TFS 2013 Object Model](https://marketplace.visualstudio.com/items?itemName=VSCSReleases.TeamFoundationServer2013Update5ObjectModelInstalle) in order to get this missing library as it's no longer available in TFS 2015, I have just try the code against TFS 2015 U2 and it seems to work fine.

Need to mention that a lot has been changed since TFS 2013, while the sample works when installing TFS 2013 Object Model it's not tested against Git repo. You may want to switch to Rest API or [Libgit2Sharp](https://github.com/libgit2/libgit2sharp)
